const KEY="futura-space-pos-v1";
const DEF=[
{id:"p1",name:"Espresso",category:"Kopi",price:18000,cost:5000,stock:80,sku:"ESP",emoji:"☕",active:true},
{id:"p2",name:"Americano",category:"Kopi",price:20000,cost:5500,stock:80,sku:"AME",emoji:"☕",active:true},
{id:"p3",name:"Cappuccino",category:"Kopi",price:25000,cost:9000,stock:80,sku:"CAP",emoji:"☕",active:true},
{id:"p4",name:"Cafe Latte",category:"Kopi",price:25000,cost:9500,stock:80,sku:"LAT",emoji:"🥛",active:true},
{id:"p5",name:"Kopi Susu Gula Aren",category:"Kopi",price:22000,cost:8000,stock:90,sku:"KSA",emoji:"🧋",active:true},
{id:"p6",name:"Future Mocha",category:"Signature",price:30000,cost:11000,stock:50,sku:"FMO",emoji:"🪐",active:true},
{id:"p7",name:"Space Cold Brew",category:"Signature",price:28000,cost:9000,stock:40,sku:"SCB",emoji:"🧊",active:true},
{id:"p8",name:"Matcha Latte",category:"Non Kopi",price:28000,cost:10000,stock:40,sku:"MAT",emoji:"🍵",active:true},
{id:"p9",name:"Chocolate",category:"Non Kopi",price:26000,cost:9000,stock:40,sku:"CHO",emoji:"🍫",active:true},
{id:"p10",name:"Lemon Tea",category:"Non Kopi",price:18000,cost:5000,stock:50,sku:"LTE",emoji:"🍋",active:true},
{id:"p11",name:"Mineral Water",category:"Non Kopi",price:8000,cost:2500,stock:60,sku:"AIR",emoji:"💧",active:true},
{id:"p12",name:"Croissant Butter",category:"Makanan",price:22000,cost:10000,stock:20,sku:"CRO",emoji:"🥐",active:true},
{id:"p13",name:"Toast Coklat Keju",category:"Makanan",price:18000,cost:8000,stock:25,sku:"TCK",emoji:"🍞",active:true},
{id:"p14",name:"French Fries",category:"Makanan",price:20000,cost:8000,stock:30,sku:"FRY",emoji:"🍟",active:true},
{id:"p15",name:"Chicken Sandwich",category:"Makanan",price:35000,cost:18000,stock:18,sku:"SND",emoji:"🥪",active:true},
{id:"p16",name:"Pasta Aglio",category:"Makanan",price:38000,cost:16000,stock:15,sku:"PAS",emoji:"🍝",active:true}
];
const SET0={shopName:"FUTURA SPACE",address:"Coffee & Space",phone:"",pin:""};
const todayISO=()=>{const d=new Date();return new Date(d-d.getTimezoneOffset()*60000).toISOString().slice(0,10)};
function load(){try{const d=JSON.parse(localStorage.getItem(KEY));if(d&&d.products){d.settings={...SET0,...(d.settings||{})};d.seq=d.seq||1;d.transactions=d.transactions||[];d.expenses=d.expenses||[];return d}}catch(e){}return{products:structuredClone(DEF),transactions:[],expenses:[],settings:{...SET0},seq:1}}
const save=()=>localStorage.setItem(KEY,JSON.stringify(DB));
let DB=load(),cart=[],activeCat="Semua",payMethod="Tunai";
const rp=n=>"Rp "+Math.round(Number(n)||0).toLocaleString("id-ID");
function toast(m){const el=document.getElementById("toast");el.textContent=m;el.classList.remove("hidden");setTimeout(()=>el.classList.add("hidden"),2000)}
const uid=p=>p+Date.now().toString(36)+Math.random().toString(36).slice(2,6);
const TITLES={dashboard:["Dashboard","Ringkasan hari ini"],kasir:["Kasir","Ambil pesanan"],produk:["Produk","Kelola menu"],transaksi:["Transaksi","Riwayat penjualan"],pembukuan:["Pembukuan","Pemasukan & pengeluaran"],laporan:["Laporan","Laba rugi"],pengaturan:["Pengaturan","Profil & backup"]};
document.querySelectorAll(".nav-btn[data-view]").forEach(b=>b.onclick=()=>showView(b.dataset.view));
document.getElementById("mobile-nav").innerHTML=[["dashboard","Home"],["kasir","Kasir"],["produk","Menu"],["transaksi","Trx"],["pembukuan","Buku"],["laporan","Laporan"],["pengaturan","Set"]].map(([v,l])=>`<button class="cat-btn" onclick="showView('${v}')">${l}</button>`).join("");
function showView(n){document.querySelectorAll(".view").forEach(v=>v.classList.remove("active"));document.getElementById("view-"+n).classList.add("active");document.querySelectorAll(".nav-btn[data-view]").forEach(b=>b.classList.toggle("active",b.dataset.view===n));document.getElementById("view-title").textContent=TITLES[n][0];document.getElementById("view-sub").textContent=TITLES[n][1];({dashboard:renderDashboard,kasir:renderKasir,produk:renderProducts,transaksi:renderTransactions,pembukuan:renderBookkeeping,laporan:renderReport,pengaturan:fillSettings}[n]||(()=>{}))()}
function tick(){document.getElementById("clock").textContent=new Date().toLocaleString("id-ID",{weekday:"short",day:"2-digit",month:"short",hour:"2-digit",minute:"2-digit",second:"2-digit"})}
setInterval(tick,1000);tick();
const inRange=(d,a,b)=>(!a||d>=a)&&(!b||d<=b);const trxDate=t=>(t.datetime||"").slice(0,10);
function renderDashboard(){const day=todayISO();const sales=DB.transactions.filter(t=>trxDate(t)===day&&!t.voided);const omzet=sales.reduce((s,t)=>s+t.total,0);const hpp=sales.reduce((s,t)=>s+t.items.reduce((a,i)=>a+i.cost*i.qty,0),0);const exp=DB.expenses.filter(e=>e.date===day).reduce((s,e)=>s+e.amount,0);
document.getElementById("stat-omzet").textContent=rp(omzet);document.getElementById("stat-trx").textContent=sales.length+" transaksi";document.getElementById("stat-laba").textContent=rp(omzet-hpp);document.getElementById("stat-exp").textContent=rp(exp);document.getElementById("stat-net").textContent=rp(omzet-hpp-exp);
const tally={};sales.forEach(t=>t.items.forEach(i=>tally[i.name]=(tally[i.name]||0)+i.qty));const top=Object.entries(tally).sort((a,b)=>b[1]-a[1]).slice(0,6);
document.getElementById("top-products").innerHTML=top.length?top.map(([n,q])=>`<div class="list-row"><span>${n}</span><b>${q} terjual</b></div>`).join(""):`<div class="muted">Belum ada penjualan hari ini.</div>`;
const recent=[...DB.transactions].reverse().slice(0,6);
document.getElementById("recent-trx").innerHTML=recent.length?recent.map(t=>`<div class="list-row"><span>${t.number} · ${t.customer||"Walk-in"}</span><b>${rp(t.total)}</b></div>`).join(""):`<div class="muted">Belum ada transaksi.</div>`;
const low=DB.products.filter(p=>p.active&&p.stock<=5);
document.getElementById("low-stock").innerHTML=low.length?low.map(p=>`<div class="chip warn">${p.emoji} ${p.name} · sisa ${p.stock}</div>`).join(""):`<div class="chip">Stok aman</div>`;
document.getElementById("shift-info").textContent=DB.settings.shopName+" · "+day}
function renderKasir(){const cats=["Semua",...new Set(DB.products.map(p=>p.category))];
document.getElementById("cat-filters").innerHTML=cats.map(c=>`<button class="cat-btn ${c===activeCat?"active":""}" onclick="setCat('${c}')">${c}</button>`).join("");
const q=(document.getElementById("search-product").value||"").toLowerCase();
const list=DB.products.filter(p=>p.active&&(activeCat==="Semua"||p.category===activeCat)&&(!q||p.name.toLowerCase().includes(q)||String(p.sku).toLowerCase().includes(q)));
document.getElementById("product-grid").innerHTML=list.map(p=>`<button class="prod-card ${p.stock<=0?"oos":""}" onclick="addToCart('${p.id}')"><div><div class="emoji">${p.emoji||"☕"}</div><div class="name">${p.name}</div></div><div><div class="price">${rp(p.price)}</div><div class="stock">stok ${p.stock}</div></div></button>`).join("");renderCart()}
function setCat(c){activeCat=c;renderKasir()}
document.getElementById("search-product").addEventListener("input",renderKasir);
function addToCart(id){const p=DB.products.find(x=>x.id===id);if(!p||p.stock<=0)return toast("Stok habis");const line=cart.find(c=>c.id===id);const used=line?line.qty:0;if(used+1>p.stock)return toast("Stok tidak cukup");if(line)line.qty++;else cart.push({id:p.id,name:p.name,price:p.price,cost:p.cost,qty:1,emoji:p.emoji});renderCart()}
function changeQty(id,d){const line=cart.find(c=>c.id===id);if(!line)return;const p=DB.products.find(x=>x.id===id);line.qty+=d;if(line.qty<=0)cart=cart.filter(c=>c.id!==id);else if(p&&line.qty>p.stock){line.qty=p.stock;toast("Melebihi stok")}renderCart()}
function clearCart(){cart=[];document.getElementById("cart-discount").value=0;document.getElementById("cust-name").value="";renderCart()}
function cartNums(){const sub=cart.reduce((s,i)=>s+i.price*i.qty,0);const disc=Math.max(0,Number(document.getElementById("cart-discount").value)||0);return{sub,disc,total:Math.max(0,sub-disc)}}
function renderCart(){const box=document.getElementById("cart-items");box.innerHTML=cart.length?cart.map(i=>`<div class="cart-line"><div><b>${i.emoji||""} ${i.name}</b><br><span class="muted">${rp(i.price)} × ${i.qty}</span></div><div><div class="qty"><button onclick="changeQty('${i.id}',-1)">−</button><span>${i.qty}</span><button onclick="changeQty('${i.id}',1)">+</button></div><div style="text-align:right;margin-top:4px">${rp(i.price*i.qty)}</div></div></div>`).join(""):`<div class="muted" style="padding:12px">Keranjang kosong.</div>`;const n=cartNums();document.getElementById("cart-sub").textContent=rp(n.sub);document.getElementById("cart-total").textContent=rp(n.total);document.getElementById("btn-checkout").disabled=!cart.length}
function openCheckout(){if(!cart.length)return;const n=cartNums();payMethod="Tunai";document.getElementById("modal-card").innerHTML=`<h3>Pembayaran</h3><p class="muted">Total</p><div class="grand" style="margin:6px 0 14px">${rp(n.total)}</div><div class="pay-grid">${["Tunai","QRIS","Transfer","Kartu"].map(m=>`<button class="pay-btn ${m==="Tunai"?"active":""}" onclick="selectPay(this,'${m}')">${m}</button>`).join("")}</div><div class="field" id="cash-wrap"><label>Uang diterima</label><input id="cash-in" type="number" min="0" value="${n.total}" oninput="updChange()"/><div style="margin-top:8px">Kembalian: <b id="change-out">${rp(0)}</b></div></div><div class="btn-row" style="margin-top:14px"><button class="btn-ghost" onclick="closeModal()">Batal</button><button class="btn-primary" onclick="confirmPay()">Konfirmasi Bayar</button></div>`;document.getElementById("modal").classList.remove("hidden");updChange()}
function selectPay(el,m){payMethod=m;document.querySelectorAll(".pay-btn").forEach(b=>b.classList.remove("active"));el.classList.add("active");document.getElementById("cash-wrap").style.display=m==="Tunai"?"block":"none"}
function updChange(){const n=cartNums();document.getElementById("change-out").textContent=rp(Math.max(0,(Number(document.getElementById("cash-in").value)||0)-n.total))}
function confirmPay(){const n=cartNums();let paid=n.total,change=0;if(payMethod==="Tunai"){paid=Number(document.getElementById("cash-in").value)||0;if(paid<n.total)return toast("Uang tunai kurang");change=paid-n.total}for(const line of cart){const p=DB.products.find(x=>x.id===line.id);if(!p||p.stock<line.qty)return toast("Stok berubah")}cart.forEach(line=>{DB.products.find(x=>x.id===line.id).stock-=line.qty});const trx={id:uid("t"),number:"FS"+String(DB.seq++).padStart(4,"0"),datetime:new Date().toISOString(),customer:document.getElementById("cust-name").value.trim(),items:cart.map(i=>({...i})),subtotal:n.sub,discount:n.disc,total:n.total,payment:payMethod,paid,change,voided:false};DB.transactions.push(trx);save();closeModal();showReceipt(trx);clearCart();renderKasir();toast("Tersimpan "+trx.number)}
function showReceipt(t){const s=DB.settings,when=new Date(t.datetime).toLocaleString("id-ID");document.getElementById("modal-card").innerHTML=`<div id="print-area" class="receipt"><h4>${s.shopName}</h4><div class="center">${s.address||""}</div><div class="center">${s.phone||""}</div><hr><div>${t.number} · ${when}</div><div>${t.customer||"Walk-in"} · ${t.payment}</div><hr>${t.items.map(i=>`<div style="display:flex;justify-content:space-between"><span>${i.qty} ${i.name}</span><span>${Math.round(i.price*i.qty).toLocaleString("id-ID")}</span></div>`).join("")}<hr><div style="display:flex;justify-content:space-between"><b>TOTAL</b><b>${Math.round(t.total).toLocaleString("id-ID")}</b></div><div style="display:flex;justify-content:space-between"><span>Bayar</span><span>${Math.round(t.paid).toLocaleString("id-ID")}</span></div><div style="display:flex;justify-content:space-between"><span>Kembali</span><span>${Math.round(t.change).toLocaleString("id-ID")}</span></div><hr><div class="center">Terima kasih<br>FUTURA SPACE</div></div><div class="btn-row" style="margin-top:14px"><button class="btn-ghost" onclick="closeModal()">Tutup</button><button class="btn-primary" onclick="window.print()">Cetak Struk</button></div>`;document.getElementById("modal").classList.remove("hidden")}
const closeModal=()=>document.getElementById("modal").classList.add("hidden");
function renderProducts(){document.getElementById("product-table").innerHTML=DB.products.map(p=>`<tr><td>${p.emoji||""} <b>${p.name}</b><br><span class="muted">${p.sku}</span></td><td>${p.category}</td><td>${rp(p.price)}</td><td>${rp(p.cost)}</td><td>${p.stock}</td><td><span class="badge ${p.active?"on":"off"}">${p.active?"Aktif":"Nonaktif"}</span></td><td><button class="btn-tiny" onclick="openProductForm('${p.id}')">Edit</button></td></tr>`).join("")}
function openProductForm(id){const p=id?DB.products.find(x=>x.id===id):null;document.getElementById("modal-card").innerHTML=`<h3>${p?"Edit Produk":"Produk Baru"}</h3><form class="form" onsubmit="saveProduct(event,'${p?p.id:""}')"><div class="field"><label>Nama</label><input id="pf-name" required value="${p?p.name:""}"></div><div class="field"><label>Kategori</label><input id="pf-cat" required value="${p?p.category:"Kopi"}"></div><div class="field"><label>SKU</label><input id="pf-sku" value="${p?p.sku:""}"></div><div class="field"><label>Emoji</label><input id="pf-emoji" value="${p?p.emoji:"☕"}"></div><div class="field"><label>Harga</label><input id="pf-price" type="number" min="0" required value="${p?p.price:0}"></div><div class="field"><label>HPP</label><input id="pf-cost" type="number" min="0" required value="${p?p.cost:0}"></div><div class="field"><label>Stok</label><input id="pf-stock" type="number" min="0" required value="${p?p.stock:0}"></div><div class="field"><label><input id="pf-active" type="checkbox" ${!p||p.active?"checked":""}> Aktif</label></div><div class="btn-row"><button type="button" class="btn-ghost" onclick="closeModal()">Batal</button><button class="btn-primary" type="submit">Simpan</button>${p?`<button type="button" class="btn-danger" onclick="deleteProduct('${p.id}')">Hapus</button>`:""}</div></form>`;document.getElementById("modal").classList.remove("hidden")}
function saveProduct(e,id){e.preventDefault();const data={name:document.getElementById("pf-name").value.trim(),category:document.getElementById("pf-cat").value.trim(),sku:document.getElementById("pf-sku").value.trim(),emoji:document.getElementById("pf-emoji").value.trim()||"☕",price:+document.getElementById("pf-price").value||0,cost:+document.getElementById("pf-cost").value||0,stock:+document.getElementById("pf-stock").value||0,active:document.getElementById("pf-active").checked};if(id)Object.assign(DB.products.find(x=>x.id===id),data);else DB.products.push({id:uid("p"),...data});save();closeModal();renderProducts();toast("Produk disimpan")}
function deleteProduct(id){if(!confirm("Hapus produk?"))return;DB.products=DB.products.filter(p=>p.id!==id);save();closeModal();renderProducts()}
function renderTransactions(){const from=document.getElementById("trx-from").value,to=document.getElementById("trx-to").value,pay=document.getElementById("trx-pay").value;const rows=[...DB.transactions].reverse().filter(t=>inRange(trxDate(t),from,to)&&(!pay||t.payment===pay));document.getElementById("trx-table").innerHTML=rows.length?rows.map(t=>`<tr style="${t.voided?"opacity:.45":""}"><td>${new Date(t.datetime).toLocaleString("id-ID")}</td><td>${t.number}${t.voided?" (void)":""}</td><td>${t.customer||"Walk-in"}</td><td>${t.items.map(i=>i.qty+"× "+i.name).join(", ")}</td><td>${rp(t.total)}</td><td>${t.payment}</td><td><button class="btn-tiny" onclick="reprint('${t.id}')">Struk</button>${t.voided?"":`<button class="btn-tiny" onclick="voidTrx('${t.id}')">Void</button>`}</td></tr>`).join(""):`<tr><td colspan="7" class="muted">Tidak ada transaksi.</td></tr>`}
function reprint(id){const t=DB.transactions.find(x=>x.id===id);if(t)showReceipt(t)}
function voidTrx(id){const t=DB.transactions.find(x=>x.id===id);if(!t||t.voided)return;if(!confirm("Void "+t.number+"?"))return;t.voided=true;t.items.forEach(i=>{const p=DB.products.find(x=>x.id===i.id);if(p)p.stock+=i.qty});save();renderTransactions();toast("Void")}
function addExpense(e){e.preventDefault();DB.expenses.push({id:uid("e"),date:document.getElementById("ex-date").value,category:document.getElementById("ex-cat").value,amount:+document.getElementById("ex-amt").value||0,note:document.getElementById("ex-note").value.trim()});save();document.getElementById("expense-form").reset();document.getElementById("ex-date").value=todayISO();renderBookkeeping();toast("Pengeluaran tercatat")}
function renderBookkeeping(){if(!document.getElementById("ex-date").value)document.getElementById("ex-date").value=todayISO();const from=document.getElementById("ex-from").value,to=document.getElementById("ex-to").value;const sales=DB.transactions.filter(t=>!t.voided&&inRange(trxDate(t),from,to));const exps=DB.expenses.filter(e=>inRange(e.date,from,to));const inn=sales.reduce((s,t)=>s+t.total,0),out=exps.reduce((s,e)=>s+e.amount,0);document.getElementById("bk-in").textContent=rp(inn);document.getElementById("bk-out").textContent=rp(out);document.getElementById("bk-net").textContent=rp(inn-out);document.getElementById("expense-list").innerHTML=exps.length?[...exps].reverse().map(e=>`<div class="list-row"><div><b>${e.category}</b><div class="muted">${e.date} · ${e.note||"-"}</div></div><div><b>${rp(e.amount)}</b><button class="btn-tiny" onclick="delExpense('${e.id}')">hapus</button></div></div>`).join(""):`<div class="muted">Belum ada pengeluaran.</div>`}
function delExpense(id){if(!confirm("Hapus pengeluaran?"))return;DB.expenses=DB.expenses.filter(e=>e.id!==id);save();renderBookkeeping()}
function periodDefaults(){const to=todayISO();const f=document.getElementById("rep-from"),t=document.getElementById("rep-to");if(!t.value)t.value=to;if(!f.value){f.value=todayISO().slice(0,8)+"01"}}
function renderReport(){periodDefaults();const from=document.getElementById("rep-from").value,to=document.getElementById("rep-to").value;const sales=DB.transactions.filter(t=>!t.voided&&inRange(trxDate(t),from,to));const exps=DB.expenses.filter(e=>inRange(e.date,from,to));const omzet=sales.reduce((s,t)=>s+t.total,0),hpp=sales.reduce((s,t)=>s+t.items.reduce((a,i)=>a+i.cost*i.qty,0),0),out=exps.reduce((s,e)=>s+e.amount,0);const byPay={};sales.forEach(t=>byPay[t.payment]=(byPay[t.payment]||0)+t.total);
document.getElementById("report-body").innerHTML=`<p class="muted">${from} s/d ${to} · ${sales.length} transaksi</p><div class="row"><span>Omzet</span><b>${rp(omzet)}</b></div><div class="row"><span>HPP</span><span>${rp(hpp)}</span></div><div class="row"><span>Laba kotor</span><b>${rp(omzet-hpp)}</b></div><div class="row"><span>Pengeluaran</span><span>${rp(out)}</span></div><div class="row total"><span>Laba bersih</span><b>${rp(omzet-hpp-out)}</b></div><h3 style="margin:18px 0 8px">Metode bayar</h3>${Object.keys(byPay).length?Object.entries(byPay).map(x=>`<div class="row"><span>${x[0]}</span><span>${rp(x[1])}</span></div>`).join(""):"<div class='muted'>Tidak ada.</div>"}`}
function printReport(){const w=window.open("","_blank");w.document.write(`<title>Laporan</title><h2>${DB.settings.shopName}</h2>`+document.getElementById("report-body").innerHTML);w.document.close();w.print()}
function fillSettings(){document.getElementById("set-name").value=DB.settings.shopName||"";document.getElementById("set-addr").value=DB.settings.address||"";document.getElementById("set-phone").value=DB.settings.phone||"";document.getElementById("set-pin").value=DB.settings.pin||""}
function saveSettings(e){e.preventDefault();DB.settings.shopName=document.getElementById("set-name").value.trim()||"FUTURA SPACE";DB.settings.address=document.getElementById("set-addr").value.trim();DB.settings.phone=document.getElementById("set-phone").value.trim();DB.settings.pin=document.getElementById("set-pin").value.trim();save();document.querySelector(".brand strong").textContent=DB.settings.shopName;toast("Pengaturan disimpan")}
function exportBackup(){const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([JSON.stringify(DB,null,2)],{type:"application/json"}));a.download=`futura-space-backup-${todayISO()}.json`;a.click()}
function importBackup(ev){const f=ev.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const data=JSON.parse(r.result);if(!data.products)throw 0;DB=data;DB.settings={...SET0,...(data.settings||{})};save();showView("dashboard");toast("Impor berhasil")}catch(e){toast("File tidak valid")}};r.readAsText(f)}
function resetDemo(){if(!confirm("Reset data demo?"))return;localStorage.removeItem(KEY);DB=load();cart=[];showView("dashboard");toast("Reset")}
function lockNow(){if(!DB.settings.pin)return toast("Set PIN di Pengaturan");sessionStorage.removeItem("fs-unlock");document.getElementById("app").classList.add("hidden");document.getElementById("lock-screen").classList.remove("hidden");document.getElementById("pin-input").value=""}
function unlock(){if(document.getElementById("pin-input").value===DB.settings.pin){sessionStorage.setItem("fs-unlock","1");document.getElementById("lock-screen").classList.add("hidden");document.getElementById("app").classList.remove("hidden")}else document.getElementById("pin-error").textContent="PIN salah"}
document.getElementById("pin-input")?.addEventListener("keydown",e=>{if(e.key==="Enter")unlock()});
["trx-from","trx-to","ex-from","ex-to"].forEach(id=>{if(!document.getElementById(id).value)document.getElementById(id).value=todayISO()});
document.getElementById("ex-date").value=todayISO();
document.querySelector(".brand strong").textContent=DB.settings.shopName;
if(DB.settings.pin&&sessionStorage.getItem("fs-unlock")!=="1"){document.getElementById("app").classList.add("hidden");document.getElementById("lock-screen").classList.remove("hidden")}
showView("dashboard");
